#!/system/bin/sh


export HOME=/sdcard
adb="/cache/adb"

su <<< "
$adb kill-server
setprop service.adb.tcp.port 5555
mkdir -p /tmp

stop adbd
start adbd
exit
"

brevent="/data/app/`pm path me.piebridge.brevent|cut -f 4 -d '/'`/lib/arm/libbootstrap.so"
$adb shell <<< "
$brevent &
setprop service.adb.tcp.port -1
su -c \"$adb kill-server;stop adbd;start adbd\"
" &
