require("Test")
require("Fraction")
require("Class")
t = new(Test)()
x = Fraction.new(-4, 8)
y = new(Fraction)(-2, -3)
z = new(Fraction)(3, -4)
t:assertEqual(x, {-1, 1, 2})
t:assertEqual(y, {1, 2, 3})
t:assertEqual(z, {-1, 3, 4})
t:assertEqual(x + y, {1, 1, 6})
t:assertEqual(x - y, {-1, 7, 6})
t:assertEqual(x * y, {-1, 1, 3})
t:assertEqual(x / y, {-1, 3, 4})
t:assertEqual(x + y, y + x)
t:assertEqual(x * y, y * x)
t:assertEqual(x + y + z, x + z + y)
t:assertEqual(x * y * z, x * z * y)
t:assertEqual(x + y + z, z + y + x)
t:assertEqual(x * y * z, z * y * x)
